apiVersion: apps/v1
kind: Deployment
metadata:
  name: midas-fastapi
  namespace: midas-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: midas-fastapi
  template:
    metadata:
      labels:
        app: midas-fastapi
    spec:
      containers:
        - name: midas-fastapi
          image: {{ .Values.fastapi.image.repository }}:{{ .Values.fastapi.image.tag }}
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: midas-fastapi
  namespace: midas-production
spec:
  selector:
    app: midas-fastapi
  ports:
    - port: 8080
      targetPort: 8080
