replicaCount: 1

image:
  repository: registry.kube-system.svc.cluster.local:5000/MIDAS-flask
  tag: staging-1.0.0

service:
  port: 8081
  externalIP: ""   # Placeholder

# resources:
#   limits:
#     cpu: "500m"
#     memory: "256Mi"
#   requests:
#     cpu: "200m"
#     memory: "128Mi"

resources:
  limits:
    cpu: "12000m"
    memory: "25Gi"
    nvidia.com/gpu: 1
  requests:
    cpu: "4000m"
    memory: "15Gi"
