# all:
#   vars:
#     ansible_python_interpreter: /usr/bin/python3
#   hosts:
#     node1:
#       ansible_host: 192.168.1.11
#       ansible_user: cc
#     node2:
#       ansible_host: 192.168.1.12
#       ansible_user: cc
#     node3:
#       ansible_host: 192.168.1.13
#       ansible_user: cc


all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    node1:
      ansible_host: 129.114.108.145
      ansible_user: cc
      ansible_ssh_private_key_file: ~/.ssh/id_rsa_chameleon_project_5