replicaCount: 1

flask:
  image:
    repository: registry.kube-system.svc.cluster.local:5000/midas-flask
    tag: production-1.0.0

fastapi:
  image:
    repository: registry.kube-system.svc.cluster.local:5000/midas-fastapi
    tag: production-1.0.0

service:
  port: 80
  externalIP: ""   # Placeholder

# resources:
#   limits:
#     cpu: "500m"
#     memory: "256Mi"
#   requests:
#     cpu: "200m"
#     memory: "128Mi"

resources:
  limits:
    cpu: "12000m"
    memory: "25Gi"
    nvidia.com/gpu: 1
  requests:
    cpu: "4000m"
    memory: "15Gi"
